version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: /Frontend/Dockerfile
    ports:
      - "3000:80" # Map localhost:3000 to container port 80
    restart: unless-stopped
  backend:
    build:
      context: .
      dockerfile: /flaud-book/Dockerfile
    container_name: fastapi_backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - storagedb
    env_file: 
      - /flaud-book/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/__pycache__

  storagedb:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file: 
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
